server:
  port: 8080
  
spring:
  data:
    mongodb:
      host: localhost
      database: schoolDB

  datasource:
    url: jdbc:mysql://localhost:3307/springdatajpa
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
